// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file is auto-generated by RiverpodGenerator and is part of the
// `auth_viewmodel.dart` file, which defines the primary authentication logic
// and state management for user authentication flows in the application.
//
// The generated code includes the `authViewModelProvider` provider instance
// and dependencies that are managed by Riverpod for optimized state handling.
// Changes to this file will be overwritten if modified by hand.
part of 'auth_viewmodel.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$authViewModelHash() => r'4ef2e067a3701792ffa70216148b060d9ce77e32';

/// See also [AuthViewModel].
@ProviderFor(AuthViewModel)
final authViewModelProvider =
    AutoDisposeNotifierProvider<AuthViewModel, AsyncValue>.internal(
  AuthViewModel.new,
  name: r'authViewModelProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$authViewModelHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$AuthViewModel = AutoDisposeNotifier<AsyncValue>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member, deprecated_member_use_from_same_package
